#!/bin/bash

# This is a work in progress - does not yet do all that needs to be done

for origin in $(git branch -a | grep origin.*JENKINS | sed 's!remotes/!!g'); do
        bug=$(echo $origin | sed -e 's!.*JENKINS!JENKINS!g' -e 's!/.*$!!g')
        branch=$(echo $origin | sed 's!origin/!!g')
        dir=$(echo $origin | sed -e 's!.*JENKINS!JENKINS!g' -e 's!/!-!g')
        ( cd .. && \
          git clone --branch $branch \
                    --single-branch \
                    --reference /var/lib/git/mwaite/bugs/jenkins-bugs.git \
                    https://github.com/MarkEWaite/jenkins-bugs \
                    $dir )
        ( cd ../$dir && \
          git config remote.origin.pushurl git@github.com:MarkEWaite/jenkins-bugs.git &&
          git remote add cache mwaite@git.markwaite.net:git/bare/bugs/jenkins-bugs.git && \
          git config remote.cache.fetch $(git config --get remote.origin.fetch | sed 's/origin/cache/g') && \
          git remote add bare /var/lib/git/mwaite/bugs/jenkins-bugs.git && \
          git config remote.bare.fetch $(git config --get remote.origin.fetch | sed 's/origin/bare/g') && \
          git pull --all --prune )
done
