#!/bin/sh

# Remove all but one tag from the stale/* tags

if [ "$1" = "" ] ; then
  echo Must provide a tag name to create
  exit 1
fi

tag_name=$1

# Set local configuration
for remote in $(git remote); do
  if ! git config --list | grep -q -i remote.$remote.fetch.*tags/stale; then
    echo Adding remote.$remote.fetch
    git config --add remote.$remote.fetch '+refs/tags/stale/*:refs/tags/stale/*'
  fi
  if ! git config --list | grep -q -i remote.$remote.tagOpt.*no-tags; then
    echo Setting remote.$remote.tagOpt --no-tags
    git config remote.$remote.tagOpt --no-tags
  fi
  if ! git config --list | grep -q -i remote.$remote.pruneTags.*true; then
    echo Setting remote.$remote.pruneTags true
    git config remote.$remote.pruneTags true
  fi
  if ! git config --list | grep -q -i alias.pull-a.*true; then
    echo Setting alias.pull-a true to hide the pull-a command in this repo
    git config alias.pull-a '!true'
  fi
done

echo
echo Remove local tags except the one allowed to remain
echo 
for tag in $(git tag | grep -v $tag_name); do
  git tag -d $tag
done

echo
echo Remove stale remote tags except the one allowed to remain
echo
for remote in $(git remote); do
  for tag in $(git ls-remote --tags $remote | grep stale/ | grep -v $tag_name | grep -F -v '^{}' | sed 's!^.*refs/tags/!!g'); do
    echo deleting tag $tag on remote $remote
    git push $remote --delete $tag
  done
done

echo
echo Create and push one allowed tag
echo
git tag -a -m "Tag $tag_name created by $0" $tag_name
for remote in $(git remote); do
  git push $remote
  git push $remote $tag_name
done
