#!/bin/bash

# Remove remote and local branches which include "JENKINS-37727-" in
# their name

for branch in $(git branch | grep -F JENKINS-37727-); do
    echo Removing local branch: $branch
    git branch -D $branch
done

git fetch --all --prune

for remote in $(git remote | sort -r); do
    for remote_branch in $(git branch -a | grep $remote.*JENKINS-37727-); do
        branch=$(echo $remote_branch | sed "s!remotes/$remote/!!g")
        echo Removing remote branch: $branch from $remote
        git push $remote :$branch
    done
done
