#!/bin/bash

# Remove remote and local branches which include "JENKINS-37727-" in
# their name

for branch in $(git branch | grep -F JENKINS-37727-); do
    echo Removing local branch: $branch
    git branch -D $branch
done

for remote_branch in $(git branch -a | grep origin.*JENKINS-37727-); do
    branch=$(echo $remote_branch | sed 's!remotes/origin/!!g')
    echo Removing remote branch: $branch
    git push origin :$branch
done
