#!/usr/bin/env bash

# Read the Jenkins log for this job, count and report git fetch calls
#
# Default Jenkins URL from JENKINS_URL environment variable
# Default Jenkins job repo URL from BUILD_URL environment variable

usage() { echo "Usage: $0 [-s jenkins_server_url] [ -j jenkins_build_url ]" 1>&2; exit 1; }

failed() { echo Failed querying $1; exit 2; }

SERVER=
JENKINS_BUILD_URL=

while getopts ":s:j:" o; do
    case "${o}" in
        s)
            SERVER=${OPTARG}
            ;;
        j)
            JENKINS_BUILD_URL=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

# Assure URL of Jenkins server is set

if [ -z "$SERVER" ]; then
    SERVER=$JENKINS_URL
fi
if [ -z "$SERVER" ]; then
    usage
fi
# remove trailing slash from SERVER, fails CSRF exclusion check
SERVER=${SERVER%/}

# Assure URL of job is set

if [ -z "$JENKINS_BUILD_URL" ]; then
    JENKINS_BUILD_URL=$BUILD_URL
fi
if [ -z "$JENKINS_BUILD_URL" ]; then
    usage
fi

if [[ $BUILD_URL == *jgit* ]]; then
    echo "Count of git fetch on agent: 1 (not really, since this uses JGit)"
    echo "Using jgit - cannot count redundant fetch operations"
    exit 0
fi

cookie_file=$(mktemp /tmp/reportGitFetchCalls-script.XXXXXX)

USER_ARG=""
args_file=""
if [ "$JENKINS_59106_USERNAME_PASSWORD" != "" ]; then
    args_file=$(mktemp /tmp/reportGitFetchCalls-args.XXXXXX)
    echo "-u $JENKINS_59106_USERNAME_PASSWORD" > $args_file
    USER_ARG="-K $args_file"
fi

crumb=$(curl --cookie-jar $cookie_file $USER_ARG -s $SERVER/crumbIssuer/api/xml?xpath=concat\(//crumbRequestField,%22:%22,//crumb\))
# echo ==== Cookie file contents
# cat $cookie_file
# echo ==== End of cookie file contents
if [ -z "$crumb" ]; then
    echo Exiting: No crumb returned by $SERVER
    exit 4
fi
if [[ $crumb =~ 'HTTP ERROR 404' ]]; then
    echo "Crumb request not answered - failing"
    echo $crumb
    echo "End of failed crumb request output - not found"
    exit 5
else
    if [[ $crumb =~ '<html>' ]]; then
        echo Exiting: html instead of crumb returned by $SERVER: $crumb
        echo "End of failed crumb request output - html"
        exit 6
    fi
    if [ ${#crumb} -gt 150 ]; then
        # First detected in Jenkins 2.190 and 2.176.3 that crumb is now over 130 characters long
        echo Long crumb returned by $SERVER: $crumb
    fi
fi

prefix=$RANDOM

# Use the crumb to query the log

echo "Querying console log with crumb $crumb"

query_output=${prefix}-crumbfull
curl -s -H "$crumb" --cookie $cookie_file $USER_ARG -X POST $JENKINS_BUILD_URL/consoleText -o $query_output

echo "==== Contents of cookie file $cookie_file"
cat $cookie_file
echo "==== End of contents of cookie file $cookie_file"

echo "==== Contents of args file $args_file"
cat $args_file
echo "==== End of contents of args file $args_file"

rm $cookie_file $args_file

echo === output from query with crumb
cat $query_output
echo === End of output from query with crumb

# Count calls to git fetch made on the agent (after 'Running on ...')
echo -n "**** Count of git fetch on agent: " ; grep -A 999 -E 'Running on |Building .*on ' $query_output | grep -c 'git fetch'

echo ===== Start of extracted git fetch commands
echo $query_output | grep git.*fetch
echo ===== End of extracted git fetch commands
