#!/bin/bash

git rm -f Jenkinsfile

if [ -h Jenkinsfile ]; then
        cp subdir/Jenkinsfile .
        commit_message="Make Jenkinsfile a copy of subdir/Jenkinsfile"
else
        ln -s subdir/Jenkinsfile .
        commit_message="Make Jenkinsfile a symlink to subdir/Jenkinsfile"
fi

git add Jenkinsfile
git commit -m $commit_message
