#!/bin/bash

if [ -h Jenkinsfile ]; then
        git rm -f Jenkinsfile
        cp subdir/Jenkinsfile .
        commit_message="Make Jenkinsfile a copy of subdir/Jenkinsfile"
else
        git rm -f Jenkinsfile
        ln -s subdir/Jenkinsfile .
        commit_message="Make Jenkinsfile a symlink to subdir/Jenkinsfile"
fi

git add Jenkinsfile
git commit -m "$commit_message"
